language: ruby
rvm:
- 2.6.5
install:
 - bundle update --jobs=3 --retry=3
bundler_args: --jobs=2
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec test
cache: bundler
services:
  - postgresql